# Site settings
title: tejjask-portfolio
tag_text: tejjask-portfolio
description: Millions of people around the world suffer from neuro-visual disorders—diseases pertaining to hindered nerves in and around the eye. Prevalent conditions in neuro-ophthalmology are described.
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
